services:
  postgres:
    image: postgres:16-alpine
    container_name: memo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: memo
      POSTGRES_PASSWORD: memo1234
      POSTGRES_DB: memo_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: memo-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: memo
      MONGO_INITDB_ROOT_PASSWORD: memo1234
      MONGO_INITDB_DATABASE: memo_db
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: memo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data:
