replicaCount: 2

image:
  repository: REGISTRY_PLACEHOLDER/memo-app/web
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3001

ingress:
  enabled: true
  className: alb
  host: ""
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: memo-app
    alb.ingress.kubernetes.io/group.order: "2"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'

resources:
  limits:
    cpu: 300m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  HOSTNAME: "0.0.0.0"
  PORT: "3001"
